sonar.projectKey=jabref-entry
sonar.projectName=JabRef (Model Entry)
sonar.projectVersion=1.0

# Avisa o Sonar que os codigos fonte estao exatamente nesta pasta (.)
sonar.sources=.

# Evita o erro de "classes nao compiladas" do Java
sonar.java.binaries=.
